* How to retrieve the HPO term related seed gene list
In order to perform the HPO term specific classification task, we need to subset our pathogenic variant file to only contain variants
associated with phenotype related genes.  
Hence, we use the [[http://phenolyzer.wglab.org/][phenolyzer]] command line tool to retrieve the list og genes associated with the HPO terms. In principle, any other tool can be used to
do this, and one could even extract a list of genes from https://hpo.jax.org/ and subset the pathogenic variant file based on these.

We used phenolyzer to be in line with what was done in our previous publication, introducing VARPP.

Just as in the VARPP 1.0 publication, the phenolyzer settings were: 
#+BEGIN_SRC 
-p -ph -logistic -addon B_DISGENET_GENE_DISEASE_SCORE,DB_GAD_GENE_DISEASE_SCORE 
-addon_weight 0.25, 
#+END_SRC
and only the genes with a known disease association were taken forward (seed genes in phenolyzer).

** Download ~phenolyzer~
#+BEGIN_SRC sh
FILE=phenolyzer
if [ -d "$FILE" ]; then
echo "$FILE already downloaded"
else
git clone https://github.com/WGLab/phenolyzer
fi
#+END_SRC

** Retrieve gene list for HPO terms
#+BEGIN_SRC sh
# Entering the phenolyzer directory
cd ../phenolyzer
# Creating an output file directory
mkdir -p HPO_genes
mkdir -p HPO_genes/out


# Variable to hold all HPO terms
filename=../hpo-obo/selected_hpo_terms.txt
all_hpo=`cat $filename`

for i in $all_hpo;
do
    echo $i
    # Run phenolyzer
    perl disease_annotation.pl $i -p -ph -logistic -addon DB_DISGENET_GENE_DISEASE_SCORE,DB_GAD_GENE_DISEASE_SCORE -addon_weight 0.25 -out HPO_genes/out_$i

done

# Create a directory for the HPO seed genes
mkdir -p ../seed_genes

# Move the seed genes for all HPO terms in to the newly created folder
cp ../phenolyzer/HPO_genes/*seed_gene_list ../seed_genes/

#+END_SRC
